### ISSUE TITLE
Incompatibility with FFmpeg 8.0

### ISSUE THREAD

**Issue by StefanBruens** [Andy1978/octave-video#5]
```
[   17s] cap_ffmpeg_impl_ov.hpp: In member function ‘void CvCapture_FFMPEG::close()’:
[   17s] cap_ffmpeg_impl_ov.hpp:655:9: error: ‘avcodec_close’ was not declared in this scope; did you mean ‘avio_close’?
[   17s]   655 |         avcodec_close( context );
[   17s]       |         ^~~~~~~~~~~~~
[   17s]       |         avio_close
[   17s] cap_ffmpeg_impl_ov.hpp: In member function ‘void CvCapture_FFMPEG::get_rotation_angle()’:
[   17s] cap_ffmpeg_impl_ov.hpp:1505:12: error: ‘av_stream_get_side_data’ was not declared in this scope; did you mean ‘av_frame_get_side_data’?
[   17s]  1505 |     data = av_stream_get_side_data(video_st, AV_PKT_DATA_DISPLAYMATRIX, NULL);
[   17s]       |            ^~~~~~~~~~~~~~~~~~~~~~~
[   17s]       |            av_frame_get_side_data
[   17s] make: *** [Makefile:12: __cap_ffmpeg_wrapper__.oct] Error 1
```

Both methods were deprecated and removed:
https://github.com/FFmpeg/FFmpeg/commit/0d48da2db0b239d80c6e8b30e66211a977566588

Also see corresponding OpenCV changes:
https://github.com/opencv/opencv/pull/27691/files

**Comment by narrenschip** [comment]
[cap_ffmpeg_impl_ov.patch](https://github.com/user-attachments/files/26374362/cap_ffmpeg_impl_ov.patch)

patch for  [video-2.1.3.tar.gz](https://github.com/Andy1978/octave-video/releases/tag/2.1.3)
`patch video-2.1.3/src/cap_ffmpeg_impl_ov.hpp cap_ffmpeg_impl_ov.patch`

based on [OpenCV  FFmpeg 8.0 support. #27691](https://github.com/opencv/opencv/pull/27691/files)

No extensive testing, but this seems to work with ffmpeg 8.0.1 and octave 11.1.0 ( ubuntu 26.04 beta ).
